---
title: "notebook"
author: "Luke"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is used to save partially developed code to the git without fully organizing and implementing it.  
```{r}
toc <- c("Reward Card Raffle",        #Ready to implement
         "24 Game",                  #Needs developed
         "Prime Functions",         #Needs developed
         "Predicting Cancellations",#Could implement, but technique isn't sound
         "Workflow Automation - Daily File Download", 
              #Needs tested across devices & networks
         "")
```


--- 
# `r toc[1]`
```{r}
# Reward Card Raffle
getRewardCardWidth <- function(){
  ret <- mean(6.5/194,
              1.95/60,
              3.2/96,
              10.2/310,
              3.41/94,
              6.35/176,
              8.8/241,
              3.20/90)
  return(ret)
}

get.seed <- function(date = Sys.Date()){
  return(as.numeric(paste0(#Data type change
    #Reformat date as a number
    strsplit(as.character(date), "-")[[1]], collapse = "")) %%
           #Mod with max integer value so value is accepted in set.seed()
           .Machine$integer.max) 
}

getRandomCard <- function(centimetersInStack, rerolls = 0){
  cardCount <- centimetersInStack/getRewardCardWidth() 
  set.seed(get.seed(lubridate::rollback(
    lubridate::rollback(Sys.Date()),
    TRUE)))
  return(sample(1:cardCount)[rerolls+1])
  #November - Nicholas - 5 total, won 3
}
interactiveDraw <- function() {
  h <- (readline(
    "How many centimeters tall is the stack of cards (To the nearest 0.01)? "))
  win <- FALSE
  n <- 0
  while(!win){
    cardN <- getRandomCard(as.numeric(h), n)
    w <- readline(paste0("Card number ", cardN, 
                         " out of ", as.numeric(h)/getRewardCardWidth()," is the winner, are they eligible (Y/N)? "))
    win <- grepl("[Yy]", w)
    n <- n+1
  }
  print(paste0("Congratulations, card number ", cardN, " is the winner!"))
}
```

``` {r eval = FALSE}
interactiveDraw()
```


---

# `r toc[2]`
```{r}
#24 Game
play24 <- function(){
  url <- "https://hub.oxen.ai/api/repos/datasets/Game-of-24/file/main/24.csv"
  filename <- paste0(mnco::cacheDir(), "/24game.csv")
  if(!file.exists(filename)) download.file(url, filename)
  
  set <- read.csv(filename)
  continue <- TRUE
  while(continue){
    starttime <- as.integer(Sys.time())
    set.seed(starttime)
    row <- set[sample(1:dim(set)[1], 1),]
    solution <- 0
    while(solution!=24){
      valid <- FALSE
      while(!valid){
        cin <- readline(paste0("How can you use:\n\t", row$Puzzles,
                             "\n\nTo create 24 using + - * / ()\n\n"))
      solution <- eval(parse(text = cin))
      valid <- TRUE
      }
    }
    endtime <- as.integer(Sys.time())
    print(paste0("Solved in ", endtime-starttime, " seconds."))
    cin <- readline("Continue (Y/N)? ")
    continue <- grepl("[Yy]", cin)
  }
}
```

---

# `r toc[3]`
```{r}
# Prime Functions
primeList <- function(){
  #From a list of primes I found
  return(readRDS("./primeList.rds"))
  }
is.prime <- function(x){
  posPrimes <- primeList()
  if(x<=1|x%%1!=0)(return(FALSE))
  if(x>posPrimes[length(posPrimes)]^2){
    stop(x, " is too large for is.prime() to check.")
  }
  posPrimes <- posPrimes[posPrimes<=ceiling(sqrt(x))]
  return(all(x%%posPrimes!=0))
}
subsetTwinPrimes <- function(primeList){
  twins <- c(primeList-2, primeList+2)
  ret <- primeList[primeList %in% twins]
  if(is.prime(primeList[1]-2)){
    ret <- c(ret,primeList[1])
  }
  return(ret)
}

getPrimeFactorization <- function(den){
  posPrimes <- 2:floor(sqrt(den))
  i <- 1
  while(i<=length(posPrimes)){
    posPrimes <- sort(c(posPrimes[i], 
                  posPrimes[which(posPrimes%%posPrimes[i]!=0, 
                               arr.ind = TRUE)]))
    i <- i+1
  }
  primes <- posPrimes[which(den%%posPrimes==0)]
  multiplicity <- sapply(primes, function(x){
                                    val <- den
                                    multi <- 0
                                    while(val%%x==0){
                                      multi <- multi+1
                                      val <- val/x
                                    }
                                    return(multi)
                                  })
  ret <- data.frame(primes, multiplicity)
  divs <- ret[den%%ret[,1]==0,1]
  den_new <- den
  for (div in divs) den_new <- den_new/div
  
  return(ret)
}
getPrimeFactorization(144)
getPrimeFactorization(144*269) #269 is prime
```


---

# `r toc[4]`

```{r}
########################### Predicting Cancellations ########################

#The following function uses the caret package to bootstrap who might 
#   cancel by training a random forest model using current data,
#   then predicting on the enrolled accounts in that current data,
#   any of those enrolled accounts that get predicted to be Inactive are 
#   returned along with a manually selected set of variables- which were 
#   chosen based on their importance in a model that was generated during 
#   development.

whoMightCancel <- function(){
  library(caret)
  library(dplyr)
  library(lubridate)
  
  if(grepl("Sandbox",getwd()))
  {setwd('..')}else if (grepl("mnco$", getwd())){
    mnco::setRawDataDir("../mcp-data/mnco-raw-data")
    mnco::setCacheDir("../mcp-data/mnco-cache")
    }
  DAT <- mnco::getCenterData()
  
  ndat <- dplyr::transmute(dplyr::filter(DAT, 
                                  .data$Enrollment_Status %in% 
                                    c("Enrolled", "Inactive")),
                    Student_Id = as.numeric(.data$Student_Id),
                    Zip = as.factor(ifelse(is.na(.data$Mailing_Zip_Code), 
                                        "NONE", .data$Mailing_Zip_Code)),
                    Grade = .data$Grade,
                    Enrollment_Status = as.factor(ifelse(
                      is.na(.data$Enrollment_Status), 
                                        "NONE", .data$Enrollment_Status)),
                    Gender = as.factor(ifelse(
                      is.na(.data$Gender), 
                                        "NONE", .data$Gender)),
                    Delivery = as.factor(ifelse(
                      is.na(.data$Delivery), 
                                        "NONE", .data$Delivery)),
                    Email_Domain = as.factor(ifelse(
                      is.na(.data$Email_Address), "NONE",
                      gsub(".*@", "", .data$Email_Address))),
                    Referred = !is.na(.data$Referral_Account),
                    Account_Created_Date = .data$Account_Created_Date,
                    Student_Created_Date = .data$Student_Created_Date,
                    Date_of_Birth = ifelse(is.na(.data$Date_of_Birth),
                                      lubridate::today()-lubridate::years(12),
                                      .data$Date_of_Birth),
                    Hold_Count = as.factor(ifelse(is.na(.data$Hold_Count), 
                                        0, .data$Hold_Count)),
                    Total_Hold_Length = ifelse(is.na(.data$Total_Hold_Length),
                                        0, .data$Total_Hold_Length),
                    Active_LPs = ifelse(is.na(.data$Active_LPs), 
                                        0, .data$Active_LPs),
                    Skills_Assigned = ifelse(is.na(.data$Skills_Assigned), 
                                        0, .data$Skills_Assigned),
                    Active_Skills_Mastered = ifelse(is.na(
                      .data$Active_Skills_Mastered), 
                                        0, .data$Active_Skills_Mastered),
                    Media_Release = !is.na(.data$Media_Release_Signature),
                    Teacher_Consent = !is.na(.data$Teacher_Consent_Signature),
                    Leave_Unescorted = !is.na(
                      .data$Leave_Unescorted_Consent_Signature))
  

  #Caret time
  set.seed(1618)
  inTrain <- caret::createDataPartition(ndat$Enrollment_Status,
                                        p = 0.8,
                                        list = FALSE)
  training <- ndat[inTrain,]
  testing <- ndat[-inTrain,]
##Probably should cache the model  
  model <- caret::train(Enrollment_Status ~ ., data = training, 
                        method = "rf", prox=TRUE)
  predictions <- predict(model, newdata = testing)
  #confusionMatrix(predictions, testing$Enrollment_Status)
            
  rtn <- dplyr::filter(ndat, .data$Enrollment_Status == "Enrolled")
  rtn <- cbind(rtn, prediction = predict(model, newdata = rtn))
  rtn <- dplyr::filter(rtn, prediction == "Inactive")
  rtn <- merge(rtn, DAT, by = "Student_Id", all.x = TRUE)
  rtn <- select(rtn, Student, Account_Created_Date.x, Total_Hold_Length.x,
                Student_Id, Student_Created_Date.x, Delivery.x, Date_of_Birth.x,
                Active_Skills_Mastered.x, Zip,Hold_Count.x, Grade.x,
                Email_Domain,Active_LPs.x, Gender.x, Referred, Leave_Unescorted,
                Teacher_Consent)
  return(rtn)
}
start <- lubridate::now()
foo <- whoMightCancel()
end <- lubridate::now()
lubridate::as.difftime(round(end-start,2))
foo
```

---

# `r toc[5]`
```{r}
downloadFiles <- function(){
  closeTab <- function(buffer = 0.5){
    KeyboardSimulator::keybd.press("Ctrl+w")
    Sys.sleep(buffer)
  }
  tab <- function(tabs=1){
    n <- 0
    while(n<tabs){
      KeyboardSimulator::keybd.press("tab")
      n <- n+1
    }
  }
  tabEnter <- function(tabs=1){
    tab(tabs)
    KeyboardSimulator::keybd.press("enter")
  }
  
  
  exStuAttendReport <- function()
  {
    browseURL("https://radius.mathnasium.com/StudentAttendanceMonthlyReport")
    Sys.sleep(2.5)
    tabEnter(14)
    Sys.sleep(3)
    tabEnter(2)
    Sys.sleep(3)
    closeTab()
  }
  
  exStuReport <- function()
  {
    browseURL("https://radius.mathnasium.com/StudentReport")
    Sys.sleep(3)
    tabEnter(10)
    Sys.sleep(10)
    tabEnter(1)
    Sys.sleep(4)
    closeTab()
  }
  
  exAssessmentReport <- function()
  {
    browseURL("https://radius.mathnasium.com/AssessmentReport")
    Sys.sleep(2.5)
    tab(9)
    Sys.sleep(0.1)
    KeyboardSimulator::keybd.press("up")
    Sys.sleep(0.5)
    tabEnter(9)
    Sys.sleep(4)
    tabEnter(1)
    Sys.sleep(3.5)
    closeTab()
  }
  
  exEnrollReport <- function(){
    browseURL("https://radius.mathnasium.com/Enrollment/EnrollmentReport")
    Sys.sleep(3)
    tabEnter(13)
    Sys.sleep(2)
    tabEnter(1)
    Sys.sleep(3)
    closeTab()
  }
  
  exCurrentBatchDetails <- function(){
    browseURL("https://radius.mathnasium.com/ProgressReportManager/CurrentBatchDetail")
    Sys.sleep(10)
    tabEnter(6)
    Sys.sleep(5)
    closeTab()
  }
  
  exAccountManagement <- function(){
    browseURL("https://radius.mathnasium.com/CustomerAccount")
    Sys.sleep(3)
    tabEnter(7)
    Sys.sleep(3)
    tabEnter(1)
    Sys.sleep(5)
    closeTab()
  }
  
  exStuManagement <- function(){
    browseURL("https://radius.mathnasium.com/Student")
    Sys.sleep(3)
    tabEnter(8)
    Sys.sleep(3)
    tabEnter(2)
    Sys.sleep(3)
    closeTab()
  }
  
  exStuAttendReport()
  exStuReport()
  exAssessmentReport()
  exEnrollReport()
  exCurrentBatchDetails()
  exAccountManagement()
  exStuManagement()
  
  Sys.sleep(0.5)
  KeyboardSimulator::keybd.press("Alt", hold = TRUE)
  Sys.sleep(0.1)
  KeyboardSimulator::keybd.press("Tab")
  Sys.sleep(0.1)
  KeyboardSimulator::keybd.release("Alt")
  Sys.sleep(0.1)
}
```

