---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mnco

<!-- badges: start -->
<!-- badges: end -->

The goal of mnco is to ...

## Installation

You can install the development version of mnco from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("PhiPrime/centerOverview")
```

## Required Data Collection

mnco relies on exported files from Radius, Mathnasium's internal operations website. You can use the below links (and applicable instuctions) to retrive all the data you'll need.

### Daily:  
[Students](https://radius.mathnasium.com/Student)  
[Accounts](https://radius.mathnasium.com/CustomerAccount)  
[Progress Report](https://radius.mathnasium.com/ProgressReportManager/CurrentBatchDetail)  
[Assessments](https://radius.mathnasium.com/AssessmentReport)  
* Select **All** in "*Pre/Post*" dropdown box  
[Enrollments](https://radius.mathnasium.com/Enrollment/EnrollmentReport)  

### Other (used for updates)  
[Assessment History](https://radius.mathnasium.com/AssessmentReport)  
* Select **All** in "*Pre/Post*" dropdown box  
* Select a date with the year **from 1970 to 2002** in "*From:*" dropdown box  
* Export and rename file to "Assessments_Prior_to_M_D_YYYY.xlsx"  
* Move file to data directory manually or with provided code  
[Payments](https://radius.mathnasium.com/Payment)  
* Not in regular routine  
[Curriculum](https://radius.mathnasium.com/CurriculumManager/CurriculumSearch)  
* Used to update curriculum database  
[Email Templates](https://radius.mathnasium.com/EmailTemplate)  
[Attendance](https://radius.mathnasium.com/StudentAttendanceMonthlyReport)  
* Used to find who has not been attending


## Package develoment notes  
1) Make: `use_r("newFunctionName")`  
2) Interactive Test: `load_all()` (`Ctrl`+`Shift`+`L`)  
* @export is included in user-facing functions  
3) Create Unit Test: `use_test()`  
4) Run Unit Test: `test()` (`Ctrl`+`Shift`+`T`) for all, or `test_active_file()` for only current.  
5) Insert Documentation Skelly: (`Ctrl`+`Shift`+`Alt`+`R`)  
6) Document with document function (`Ctrl`+`Shift`+`D`)  
7) Check with check function (`Ctrl`+`Shift`+`E`)  
8) Build with `install()` (`Ctrl`+`Shift`+`B`)  
